#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 06, 2018 01:12:05 PM

import tkinter.messagebox as tm
from tkinter import filedialog
import tkinter_support
from SetProject import *

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def vp_stProjectt_gui():
    '''StProjectting point when module is the main routine.'''
    global val, w, root
    root = Tk() 
    top = Project_Tool (root)
    tkinter_support.init(root, top)
    root.mainloop()
    

w = None
def create_Project_Tool(root, *Projectgs, **kwProjectgs):
    '''StProjectting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Project_Tool (w)
    tkinter_support.init(w, top, *Projectgs, **kwProjectgs)
    return (w, top)

def destroy_Project_Tool():
    root.destroy()
    exit()


class Project_Tool:
    
    
    
    def StProjecttButtonAction(self):
        
        
        self.Button1.config(state=DISABLED)
        
        selectedChoiceServer = ""
        if self.choice.get()==1:
            selectedChoiceServer = ''    
        if self.choice.get()==2:
            selectedChoiceServer = ''   
        if self.choice.get()==3:
            selectedChoiceServer = ''   
        if self.choice.get()==4:
            selectedChoiceServer = ''   
        if self.choice.get()==5:
            selectedChoiceServer = ''   
            
        selectedChoiceDatabase = self.Text1.get('1.0','end-1c')
        selectedChoiceSchema =   self.Text2.get('1.0','end-1c')  
        
        root.fileName = filedialog.askopenfilename( filetypes = ( ("excel files", "*.xlsx"),("All files","*.*") ) )
        
        res = import_excel(selectedChoiceServer, selectedChoiceDatabase, selectedChoiceSchema, root.fileName)
         
        if res == 1:
            messagebox.showinfo("Click OK", "Project is Set")
        else:
            messagebox.showinfo("Error: ",res)
        
        
        
        
#        print(selectedChoiceServer)
#        print(selectedChoiceDatabase)
#        print(selectedChoiceSchema)
#        print(root.fileName)
        
        
        
        
        
        
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("600x450+761+233")
        top.title("Project Tool")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")    
        top.configure(highlightcolor="black")


        self.choice = IntVProject()
        self.databaseChoice = StringVProject()
        
        
        self.Radiobutton1 = Radiobutton(top)
        self.Radiobutton1.place(relx=0.02, rely=0.07, relheight=0.07
                , relwidth=0.21)
        self.Radiobutton1.configure(activebackground="#d9d9d9")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify=LEFT)
        self.Radiobutton1.configure(text='''''')
        self.Radiobutton1.configure(vProjectiable=self.choice,value=1)

        self.Radiobutton2 = Radiobutton(top)
        self.Radiobutton2.place(relx=0.23, rely=0.07, relheight=0.07
                , relwidth=0.14)
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify=LEFT)
        self.Radiobutton2.configure(text='''''')
        self.Radiobutton2.configure(vProjectiable=self.choice,value=2)

        self.Radiobutton3 = Radiobutton(top)
        self.Radiobutton3.place(relx=0.43, rely=0.07, relheight=0.07
                , relwidth=0.14)
        self.Radiobutton3.configure(activebackground="#d9d9d9")
        self.Radiobutton3.configure(activeforeground="#000000")
        self.Radiobutton3.configure(background="#d9d9d9")
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(foreground="#000000")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="black")
        self.Radiobutton3.configure(justify=LEFT)
        self.Radiobutton3.configure(text='''''')
        self.Radiobutton3.configure(vProjectiable=self.choice,value=3)

        self.Radiobutton4 = Radiobutton(top)
        self.Radiobutton4.place(relx=0.63, rely=0.07, relheight=0.07
                , relwidth=0.14)
        self.Radiobutton4.configure(activebackground="#d9d9d9")
        self.Radiobutton4.configure(activeforeground="#000000")
        self.Radiobutton4.configure(background="#d9d9d9")
        self.Radiobutton4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton4.configure(foreground="#000000")
        self.Radiobutton4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton4.configure(highlightcolor="black")
        self.Radiobutton4.configure(justify=LEFT)
        self.Radiobutton4.configure(text='''''')
        self.Radiobutton4.configure(vProjectiable=self.choice,value=4)

        self.Radiobutton5 = Radiobutton(top)
        self.Radiobutton5.place(relx=0.8, rely=0.07, relheight=0.07
                , relwidth=0.14)
        self.Radiobutton5.configure(activebackground="#d9d9d9")
        self.Radiobutton5.configure(activeforeground="#000000")
        self.Radiobutton5.configure(background="#d9d9d9")
        self.Radiobutton5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton5.configure(foreground="#000000")
        self.Radiobutton5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton5.configure(highlightcolor="black")
        self.Radiobutton5.configure(justify=LEFT)
        self.Radiobutton5.configure(text='''''')
        self.Radiobutton5.configure(vProjectiable=self.choice,value=5)

        self.Label1 = Label(top)
        self.Label1.place(relx=0.32, rely=0.38, height=26, width=58)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Schema''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.3, rely=0.24, height=26, width=69)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Database''')

        self.Text1 = Text(top)
        self.Text1.place(relx=0.45, rely=0.24, relheight=0.05, relwidth=0.39)
        self.Text1.configure(background="#ffffffffffff")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(width=234)
        self.Text1.configure(wrap=WORD)
       

        self.Text2 = Text(top)
        self.Text2.place(relx=0.45, rely=0.38, relheight=0.05, relwidth=0.39)
        self.Text2.configure(background="white")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="#d9d9d9")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="#c4c4c4")
        self.Text2.configure(selectforeground="black")
        self.Text2.configure(width=234)
        self.Text2.configure(wrap=WORD)
        

        self.Button1 = Button(top)
        self.Button1.place(relx=0.4, rely=0.58, height=33, width=186)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''StProjectt''')
        self.Button1.configure(width=186)
        self.Button1.configure(command = self.StProjecttButtonAction)
        
        
        self.Button2 = Button(top)
        self.Button2.place(relx=0.4, rely=0.68, height=33, width=186)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Quit''')
        self.Button2.configure(width=186)
        self.Button2.configure(command = destroy_Project_Tool)
        







if __name__ == '__main__':
    vp_stProjectt_gui()



